FROM golang:alpine as build

WORKDIR /

COPY . .

RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
#RUN CGO_ENABLED=0 go get -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o ./app ./cmd/dbasik-api 

FROM scratch
COPY --from=build /go/bin/dlv /dlv
COPY --from=build /app /app
CMD ["/dlv"]
