services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - dbasik_data:/var/lib/postgresql/data
      - ./migrations:/dbasik
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    restart: "unless-stopped"
    command: "/dlv --listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./app"
    ports:
      - 2345:2345
    depends_on:
      - db
volumes:
  dbasik_data:
